on:
  issue_comment:
    types: [created, deleted] 
    
name: Azure/CLI - the actual repo

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

    - uses: azure/login@v1
      with:
        creds: ${{ secrets.Azure_cred_login_obj }}

    - name: Azure cli
      uses: azure/CLI@v0-beta
      with:
        azcliversion: 2.0.68
        inlineScript: |
          az vm create -n MyVM -g MyResourceGroup --admin-password ${{ secrets.Azure_VM_Password }} --image UbuntuLTS
 
